# Generated by Django 5.2.6 on 2025-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("MEMBER", "Member"), ("MANAGER", "Manager")],
                default="MEMBER",
                max_length=50,
            ),
        ),
    ]
