# Generated by Django 5.2.6 on 2025-09-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
