# Generated by Django 5.2.6 on 2025-09-10 16:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanGuarantor',
            new_name='Guarantor',
        ),
    ]
