# Generated by Django 5.2.6 on 2025-09-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_loanguarantor_guarantor'),
        
    ]

