# Generated by Django 5.2.6 on 2025-09-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanaccount_transaction_b2c_and_more'),
    ]

 
