# Generated by Django 5.2.6 on 2025-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loanaccount_transaction_b2c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='loan_reason',
            field=models.CharField(blank=True, help_text='If emergency, specify reason (e.g., urgent medical bill for a family member)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan_type',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20),
        ),
    ]
