# Generated by Django 5.2.6 on 2025-09-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_loanaccount_loan_reason_loanaccount_loan_type"),
        ("transaction", "0003_transaction_account_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guarantor",
            name="guarantor_id",
        ),
        migrations.RemoveField(
            model_name="loanaccount",
            name="loan_id",
        ),
        migrations.RemoveField(
            model_name="loanrepayment",
            name="repayment_id",
        ),
        migrations.AddField(
            model_name="guarantor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="transaction_id_b2c",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disbursed_loans",
                to="transaction.transaction",
            ),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_repayments",
                to="transaction.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="guarantor",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Expired", "Expired"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="loanaccount",
            name="loan_reason",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loanaccount",
            name="loan_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_GUARANTOR", "Pending Guarantor Approval"),
                    ("PENDING_MANAGER", "Pending Manager Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("DISBURSED", "Disbursed"),
                    ("COMPLETED", "Completed"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
