# Generated by Django 5.2.6 on 2025-09-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_remove_guarantor_guarantor_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanaccount",
            name="frequency_of_payment",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="repayment_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
